# Generated by Django 6.0.5 on 2026-08-12 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missao', '0001_initial'),
        ('sorteio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='sorteio.grupo'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='missao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='missao.missao'),
        ),
    ]
