# Generated by Django 6.0.5 on 2026-08-26 15:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.CharField(max_length=10, unique=True)),
                ('data_nascimento', models.DateField()),
                ('curso', models.CharField(choices=[('PEDAGOGIA', 'Pedagogia'), ('ENFERMAGEM', 'Enfermagem'), ('DIREITO', 'Direito'), ('ADS', 'Ads'), ('PSICOLOGIA', 'Psicologia'), ('PEDAGOGIA_EAD', 'Pedagogia EAD')], max_length=25)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_aluno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EdicaoSorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('turno', models.CharField(choices=[('MATUTINO', 'Matutino'), ('NOTURNO', 'Noturno')], max_length=10)),
                ('ativa', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativa', True)), fields=('turno',), name='uma_edicao_ativa_por_turno')],
            },
        ),
        migrations.CreateModel(
            name='Eixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_eixo', models.CharField(max_length=100)),
                ('ordem', models.PositiveSmallIntegerField()),
                ('quantidade_grupos', models.PositiveSmallIntegerField(default=4)),
                ('capacidade_grupo', models.PositiveSmallIntegerField(default=10)),
                ('ativo', models.BooleanField(default=True)),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eixos', to='sorteio.edicaosorteio')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('eixo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='sorteio.eixo')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='InscricaoSorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_sorteio', to='sorteio.aluno')),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='sorteio.edicaosorteio')),
                ('eixo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='sorteio.eixo')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='sorteio.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_professor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='eixo',
            constraint=models.UniqueConstraint(fields=('edicao', 'ordem'), name='eixo_ordem_unica_por_edicao'),
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('eixo', 'numero'), name='grupo_numero_unico_por_eixo'),
        ),
        migrations.AddConstraint(
            model_name='inscricaosorteio',
            constraint=models.UniqueConstraint(fields=('aluno', 'edicao'), name='aluno_um_sorteio_por_edicao'),
        ),
    ]
