# Generated by Django 6.0.5 on 2026-08-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='turno',
            field=models.CharField(choices=[('MATUTINO', 'Matutino'), ('NOTURNO', 'Noturno')], default='NOTURNO', max_length=10),
            preserve_default=False,
        ),
    ]
