# Generated by Django 6.0.5 on 2026-09-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0002_aluno_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='eixo',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descreva para que serve este eixo.', null=True),
        ),
        migrations.AddField(
            model_name='eixo',
            name='professores_responsaveis',
            field=models.CharField(blank=True, help_text='Digite os nomes dos professores responsáveis separados por vírgula.', max_length=255, null=True),
        ),
    ]
